openapi: 3.0.0
info:
  title: 'Crowdin API v1'
  description: "(Unofficial) OpenAPI schema for the v1 Crowdin API."
paths:
  
  '/api/project/{project-identifier}/add-file':
    post:
      summary: 'Add a file to your project.'
      operationId: api.projects.files.add
  
  '/api/project/{projectIdentifier}/info':
    post:
      summary: 'Get project details.'
      operationId: api.projects.getDetails
      parameters:
        -
          name: projectIdentifier
          in: path
          required: true
        -
          name: key
          in: query
          required: true